/**
 * U.S. credit card catalog for CardFind.
 * All cards are issued in the United States.
 * Apply links point to official U.S. issuer product pages.
 * Visuals use styled mock cards (brand colors) — no trademarked art.
 */
const CREDIT_CARDS = [
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred®",
    issuer: "Chase",
    issuerFull: "JPMorgan Chase Bank, N.A.",
    country: "US",
    network: "Visa",
    annualFee: 95,
    welcomeBonus: "60,000 points",
    welcomeBonusValue: 750,
    apr: "19.49%–28.24% variable",
    rating: 4.9,
    categories: ["travel", "points", "dining"],
    topFor: "travel",
    highlights: [
      "5x on travel through Chase",
      "3x on dining & online groceries",
      "2x on other travel",
      "Transfer partners for premium travel",
    ],
    description:
      "The gold standard mid-tier travel card. Flexible Ultimate Rewards points and a manageable annual fee.",
    applyUrl: "https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred",
    gradient: "linear-gradient(135deg, #0a2540 0%, #1a4a7a 45%, #2d6a9f 100%)",
    accent: "#6eb5ff",
  },
  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve®",
    issuer: "Chase",
    network: "Visa",
    annualFee: 550,
    welcomeBonus: "60,000 points",
    welcomeBonusValue: 900,
    apr: "21.49%–28.49% variable",
    rating: 4.8,
    categories: ["travel", "points", "premium", "dining"],
    topFor: null,
    highlights: [
      "$300 annual travel credit",
      "10x on hotels & car rentals via Chase",
      "3x on travel & dining",
      "Priority Pass & lounge access",
    ],
    description:
      "Premium travel powerhouse with strong credits, lounge access, and high-value point transfers.",
    applyUrl: "https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve",
    gradient: "linear-gradient(135deg, #1a1a1a 0%, #3d3d3d 50%, #5a4a2a 100%)",
    accent: "#c9a227",
  },
  {
    id: "amex-platinum",
    name: "The Platinum Card® from American Express",
    issuer: "American Express",
    network: "Amex",
    annualFee: 695,
    welcomeBonus: "80,000 Membership Rewards® points",
    welcomeBonusValue: 1200,
    apr: "See terms",
    rating: 4.7,
    categories: ["travel", "points", "premium"],
    topFor: null,
    highlights: [
      "$200 hotel credit & airline fee credit",
      "Centurion / Priority Pass lounges",
      "5x on flights booked direct or Amex Travel",
      "Fine Hotels + Resorts benefits",
    ],
    description:
      "Ultra-premium lifestyle card packed with travel credits and elite lounge access for frequent flyers.",
    applyUrl: "https://www.americanexpress.com/us/credit-cards/card/platinum/",
    gradient: "linear-gradient(135deg, #6b6b6b 0%, #a8a8a8 40%, #e8e8e8 100%)",
    accent: "#111111",
    textDark: true,
  },
  {
    id: "capital-one-venture-x",
    name: "Capital One Venture X Rewards",
    issuer: "Capital One",
    network: "Visa",
    annualFee: 395,
    welcomeBonus: "75,000 miles",
    welcomeBonusValue: 750,
    apr: "19.99%–29.99% variable",
    rating: 4.9,
    categories: ["travel", "points", "premium"],
    topFor: null,
    highlights: [
      "2x miles on every purchase",
      "10x hotels & rental cars via Capital One Travel",
      "$300 annual travel credit",
      "Capital One Lounges + Priority Pass",
    ],
    description:
      "Excellent premium travel value — lounge access and a travel credit that often offsets the fee.",
    applyUrl: "https://www.capitalone.com/credit-cards/venture-x/",
    gradient: "linear-gradient(135deg, #0d1b2a 0%, #1b3a4b 50%, #415a77 100%)",
    accent: "#7ec8e3",
  },
  {
    id: "capital-one-venture",
    name: "Capital One Venture Rewards",
    issuer: "Capital One",
    network: "Visa",
    annualFee: 95,
    welcomeBonus: "75,000 miles",
    welcomeBonusValue: 750,
    apr: "19.99%–29.99% variable",
    rating: 4.6,
    categories: ["travel", "points"],
    topFor: null,
    highlights: [
      "2x miles on every purchase",
      "5x on hotels & rental cars via Capital One Travel",
      "Transfer to 15+ airline & hotel partners",
      "No foreign transaction fees",
    ],
    description:
      "Simple flat-rate travel miles with flexible redemptions and solid transfer partners.",
    applyUrl: "https://www.capitalone.com/credit-cards/venture/",
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    accent: "#e94560",
  },
  {
    id: "amex-gold",
    name: "American Express® Gold Card",
    issuer: "American Express",
    network: "Amex",
    annualFee: 325,
    welcomeBonus: "60,000 Membership Rewards® points",
    welcomeBonusValue: 900,
    apr: "See terms",
    rating: 4.8,
    categories: ["dining", "groceries", "points"],
    topFor: "dining",
    highlights: [
      "4x at restaurants worldwide",
      "4x at U.S. supermarkets (up to $25k/yr)",
      "3x on flights booked direct or Amex Travel",
      "Up to $120 dining credit + Uber Cash",
    ],
    description:
      "Best-in-class dining and grocery earn rates for food lovers who want Membership Rewards points.",
    applyUrl: "https://www.americanexpress.com/us/credit-cards/card/gold-card/",
    gradient: "linear-gradient(135deg, #8b6914 0%, #c9a227 45%, #e8d48b 100%)",
    accent: "#3d2b00",
    textDark: true,
  },
  {
    id: "citi-double-cash",
    name: "Citi Double Cash® Card",
    issuer: "Citi",
    network: "Mastercard",
    annualFee: 0,
    welcomeBonus: "None (ongoing 2%)",
    welcomeBonusValue: 0,
    apr: "18.24%–28.24% variable",
    rating: 4.7,
    categories: ["cashback", "no-fee"],
    topFor: "cashback",
    highlights: [
      "2% cash back on every purchase",
      "1% when you buy + 1% when you pay",
      "No annual fee",
      "No rotating categories to track",
    ],
    description:
      "Straightforward unlimited 2% cash back with no annual fee — a longtime everyday favorite.",
    applyUrl: "https://www.citi.com/credit-cards/citi-double-cash-credit-card",
    gradient: "linear-gradient(135deg, #003b70 0%, #0055a5 50%, #0077c8 100%)",
    accent: "#7ec8ff",
  },
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited®",
    issuer: "Chase",
    network: "Visa",
    annualFee: 0,
    welcomeBonus: "$200 cash back",
    welcomeBonusValue: 200,
    apr: "19.49%–28.24% variable",
    rating: 4.7,
    categories: ["cashback", "no-fee", "dining", "travel"],
    topFor: null,
    highlights: [
      "5% on travel through Chase",
      "3% on dining & drugstores",
      "1.5% on everything else",
      "Ultimate Rewards ecosystem friendly",
    ],
    description:
      "Flexible no-fee card that pairs perfectly with Sapphire cards for bonus point transfer.",
    applyUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited",
    gradient: "linear-gradient(135deg, #0d4f3c 0%, #1a7a5c 50%, #2d9b6f 100%)",
    accent: "#7dffb3",
  },
  {
    id: "blue-cash-preferred",
    name: "Blue Cash Preferred® Card from American Express",
    issuer: "American Express",
    network: "Amex",
    annualFee: 95,
    welcomeBonus: "$250 statement credit",
    welcomeBonusValue: 250,
    apr: "19.24%–29.24% variable",
    rating: 4.6,
    categories: ["cashback", "groceries", "gas", "streaming"],
    topFor: "groceries",
    highlights: [
      "6% at U.S. supermarkets (up to $6k/yr)",
      "6% on select U.S. streaming",
      "3% on transit & U.S. gas stations",
      "1% on other purchases",
    ],
    description:
      "Standout cash-back rates for groceries and streaming — ideal for household spenders.",
    applyUrl: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
    gradient: "linear-gradient(135deg, #003087 0%, #0055b8 50%, #4a90d9 100%)",
    accent: "#a8d4ff",
  },
  {
    id: "wells-fargo-active-cash",
    name: "Wells Fargo Active Cash® Card",
    issuer: "Wells Fargo",
    network: "Visa",
    annualFee: 0,
    welcomeBonus: "$200 cash rewards",
    welcomeBonusValue: 200,
    apr: "20.24%–29.99% variable",
    rating: 4.5,
    categories: ["cashback", "no-fee"],
    topFor: null,
    highlights: [
      "Unlimited 2% cash rewards on purchases",
      "No annual fee",
      "Cell phone protection (eligible plans)",
      "Up to $600 cell phone protection",
    ],
    description:
      "Clean unlimited 2% cash rewards with a welcome bonus and useful phone protection perk.",
    applyUrl: "https://creditcards.wellsfargo.com/active-cash-credit-card/",
    gradient: "linear-gradient(135deg, #d71e28 0%, #b01018 40%, #4a0a0e 100%)",
    accent: "#ffb3b8",
  },
  {
    id: "discover-it-cash-back",
    name: "Discover it® Cash Back",
    issuer: "Discover",
    network: "Discover",
    annualFee: 0,
    welcomeBonus: "Cashback Match first year",
    welcomeBonusValue: 300,
    apr: "17.24%–28.24% variable",
    rating: 4.6,
    categories: ["cashback", "no-fee", "gas", "groceries"],
    topFor: null,
    highlights: [
      "5% rotating categories (up to $1,500/qtr)",
      "1% on all other purchases",
      "Cashback Match — Discover doubles first year",
      "No annual fee, Free FICO score",
    ],
    description:
      "Category cash back with first-year Cashback Match — effectively doubles your rewards year one.",
    applyUrl: "https://www.discover.com/credit-cards/cash-back/it-card.html",
    gradient: "linear-gradient(135deg, #1a1a1a 0%, #333 40%, #ff6600 100%)",
    accent: "#ff9944",
  },
  {
    id: "capital-one-savor",
    name: "Capital One Savor Cash Rewards",
    issuer: "Capital One",
    network: "Mastercard",
    annualFee: 95,
    welcomeBonus: "$200 cash bonus",
    welcomeBonusValue: 200,
    apr: "19.99%–29.99% variable",
    rating: 4.6,
    categories: ["dining", "cashback", "entertainment", "groceries"],
    topFor: null,
    highlights: [
      "3% on dining, entertainment, popular streaming",
      "3% at grocery stores",
      "1% on other purchases",
      "No foreign transaction fees",
    ],
    description:
      "Strong everyday cash back for dining out, entertainment, and groceries.",
    applyUrl: "https://www.capitalone.com/credit-cards/savor/",
    gradient: "linear-gradient(135deg, #2d1b4e 0%, #5b2d8e 50%, #8b5cf6 100%)",
    accent: "#c4b5fd",
  },
  {
    id: "citi-custom-cash",
    name: "Citi Custom Cash® Card",
    issuer: "Citi",
    network: "Mastercard",
    annualFee: 0,
    welcomeBonus: "$200 cash back",
    welcomeBonusValue: 200,
    apr: "18.24%–28.24% variable",
    rating: 4.5,
    categories: ["cashback", "no-fee", "gas", "groceries", "dining"],
    topFor: "gas",
    highlights: [
      "5% on top eligible spend category (up to $500/billing cycle)",
      "1% on other purchases",
      "Auto-selects your highest category",
      "No annual fee",
    ],
    description:
      "Automatically rewards your highest spend category at 5% — great for gas, groceries, or dining.",
    applyUrl: "https://www.citi.com/credit-cards/citi-custom-cash-credit-card",
    gradient: "linear-gradient(135deg, #0a3d62 0%, #1e5f8a 50%, #3c8dbc 100%)",
    accent: "#7ec8e3",
  },
  {
    id: "amex-blue-business-cash",
    name: "Blue Business Cash™ Card from American Express",
    issuer: "American Express",
    network: "Amex",
    annualFee: 0,
    welcomeBonus: "$250 statement credit",
    welcomeBonusValue: 250,
    apr: "17.49%–25.49% variable",
    rating: 4.5,
    categories: ["business", "cashback", "no-fee"],
    topFor: "business",
    highlights: [
      "2% cash back on the first $50,000 in purchases/yr",
      "1% thereafter",
      "No annual fee",
      "Employee cards at no extra cost",
    ],
    description:
      "Simple business cash back with no annual fee — solid starter card for freelancers and small businesses.",
    applyUrl: "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-blue-business-cash-credit-card-amex/",
    gradient: "linear-gradient(135deg, #0c2340 0%, #1a3a5c 50%, #2e5a8a 100%)",
    accent: "#6eb5ff",
  },
  {
    id: "chase-ink-business-preferred",
    name: "Ink Business Preferred® Credit Card",
    issuer: "Chase",
    network: "Visa",
    annualFee: 95,
    welcomeBonus: "100,000 points",
    welcomeBonusValue: 1000,
    apr: "19.49%–25.49% variable",
    rating: 4.7,
    categories: ["business", "points", "travel"],
    topFor: null,
    highlights: [
      "3x on the first $150k combined in travel, shipping, ads, telecom, internet",
      "1x on other purchases",
      "Transfer to Ultimate Rewards partners",
      "Primary rental car insurance",
    ],
    description:
      "Top business points card for advertising, shipping, and travel spend with transferable rewards.",
    applyUrl: "https://creditcards.chase.com/business-credit-cards/ink/business-preferred",
    gradient: "linear-gradient(135deg, #1a2744 0%, #2c3e6b 50%, #4a6fa5 100%)",
    accent: "#9ec5ff",
  },
  {
    id: "discover-it-student",
    name: "Discover it® Student Cash Back",
    issuer: "Discover",
    network: "Discover",
    annualFee: 0,
    welcomeBonus: "Cashback Match first year",
    welcomeBonusValue: 200,
    apr: "17.24%–26.24% variable",
    rating: 4.4,
    categories: ["student", "cashback", "no-fee", "gas", "groceries"],
    topFor: "student",
    highlights: [
      "5% rotating categories (activate each quarter)",
      "1% on other purchases",
      "Cashback Match first year",
      "Good Grade Reward — $20 statement credit",
    ],
    description:
      "Student-friendly cash back with Cashback Match and a good-grades reward — no annual fee.",
    applyUrl: "https://www.discover.com/credit-cards/student/it-card.html",
    gradient: "linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 40%, #ff6600 100%)",
    accent: "#ffaa66",
  },
  {
    id: "capital-one-quicksilver",
    name: "Capital One Quicksilver Cash Rewards",
    issuer: "Capital One",
    network: "Visa",
    annualFee: 0,
    welcomeBonus: "$200 cash bonus",
    welcomeBonusValue: 200,
    apr: "19.99%–29.99% variable",
    rating: 4.4,
    categories: ["cashback", "no-fee"],
    topFor: null,
    highlights: [
      "Unlimited 1.5% cash back on every purchase",
      "No annual fee",
      "No foreign transaction fees",
      "Fraud coverage & virtual card numbers",
    ],
    description:
      "Simple unlimited cash back with no foreign transaction fees — great for everyday and travel spenders.",
    applyUrl: "https://www.capitalone.com/credit-cards/quicksilver/",
    gradient: "linear-gradient(135deg, #c0c0c0 0%, #e8e8e8 40%, #a8b0b8 100%)",
    accent: "#333333",
    textDark: true,
  },
  {
    id: "chase-freedom-flex",
    name: "Chase Freedom Flex®",
    issuer: "Chase",
    network: "Mastercard",
    annualFee: 0,
    welcomeBonus: "$200 cash back",
    welcomeBonusValue: 200,
    apr: "19.49%–28.24% variable",
    rating: 4.5,
    categories: ["cashback", "no-fee", "dining", "travel"],
    topFor: null,
    highlights: [
      "5% rotating quarterly categories (up to $1,500)",
      "5% on travel through Chase",
      "3% on dining & drugstores",
      "1% on everything else",
    ],
    description:
      "Category bonuses plus fixed dining and travel earn — strong no-fee companion to Sapphire cards.",
    applyUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/flex",
    gradient: "linear-gradient(135deg, #0a3d2e 0%, #0f5c42 50%, #1a8a62 100%)",
    accent: "#5dffb0",
  },
  {
    id: "amex-green",
    name: "American Express® Green Card",
    issuer: "American Express",
    network: "Amex",
    annualFee: 150,
    welcomeBonus: "40,000 Membership Rewards® points",
    welcomeBonusValue: 600,
    apr: "See terms",
    rating: 4.3,
    categories: ["travel", "points", "dining"],
    topFor: null,
    highlights: [
      "3x on travel including transit, rideshare, flights, hotels",
      "3x at restaurants worldwide",
      "CLEAR® Plus credit",
      "LoungeBuddy credit",
    ],
    description:
      "Mid-tier Amex for travelers who want broad 3x travel and dining without Platinum-level fees.",
    applyUrl: "https://www.americanexpress.com/us/credit-cards/card/green/",
    gradient: "linear-gradient(135deg, #1a3d2a 0%, #2d5a3d 50%, #4a7c59 100%)",
    accent: "#a8e6c0",
  },
  {
    id: "bank-of-america-customized-cash",
    name: "Bank of America® Customized Cash Rewards",
    issuer: "Bank of America",
    network: "Visa",
    annualFee: 0,
    welcomeBonus: "$200 online cash rewards bonus",
    welcomeBonusValue: 200,
    apr: "18.24%–28.24% variable",
    rating: 4.3,
    categories: ["cashback", "no-fee", "gas", "groceries", "dining"],
    topFor: null,
    highlights: [
      "3% in your choice category (gas, online shopping, dining, travel, drug stores, or home improvement)",
      "2% at grocery stores & wholesale clubs",
      "1% on other purchases",
      "Preferred Rewards can boost rates up to 75%",
    ],
    description:
      "Choose your 3% category and earn 2% on groceries — even better with Preferred Rewards.",
    applyUrl: "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/",
    gradient: "linear-gradient(135deg, #012169 0%, #e31837 100%)",
    accent: "#ffffff",
  },
  {
    id: "amazon-prime-visa",
    name: "Amazon Prime Visa",
    issuer: "Chase",
    network: "Visa",
    annualFee: 0,
    welcomeBonus: "$100 Amazon gift card (Prime members)",
    welcomeBonusValue: 100,
    apr: "19.49%–27.49% variable",
    rating: 4.6,
    categories: ["cashback", "no-fee", "shopping"],
    topFor: null,
    keywords: ["amazon", "prime", "online shopping", "whole foods", "usa", "united states"],
    highlights: [
      "5% back at Amazon.com & Whole Foods (Prime)",
      "2% at restaurants, gas stations & local transit",
      "1% on other purchases",
      "No annual fee",
    ],
    description:
      "Top U.S. shopping card for Amazon Prime members — strong cash back at Amazon and Whole Foods.",
    applyUrl: "https://www.amazon.com/dp/BT00LN946S",
    gradient: "linear-gradient(135deg, #232f3e 0%, #37475a 50%, #ff9900 100%)",
    accent: "#ff9900",
  },
  {
    id: "costco-anywhere-visa",
    name: "Costco Anywhere Visa® Card by Citi",
    issuer: "Citi",
    network: "Visa",
    annualFee: 0,
    welcomeBonus: "None (ongoing rewards)",
    welcomeBonusValue: 0,
    apr: "19.24%–29.24% variable",
    rating: 4.5,
    categories: ["cashback", "no-fee", "gas", "travel", "groceries"],
    topFor: null,
    keywords: ["costco", "warehouse", "usa", "gas stations", "ev charging"],
    highlights: [
      "4% on gas & EV charging (up to $7,000/yr)",
      "3% on restaurants & eligible travel",
      "2% on Costco purchases",
      "1% on everything else — annual reward certificate",
    ],
    description:
      "Built for Costco members in the U.S. — strong gas and travel cash back with rewards paid yearly.",
    applyUrl: "https://www.citi.com/credit-cards/citi-costco-anywhere-visa-credit-card",
    gradient: "linear-gradient(135deg, #003b70 0%, #e31837 100%)",
    accent: "#ffffff",
  },
  {
    id: "apple-card",
    name: "Apple Card",
    issuer: "Goldman Sachs",
    network: "Mastercard",
    annualFee: 0,
    welcomeBonus: "None (ongoing Daily Cash)",
    welcomeBonusValue: 0,
    apr: "18.24%–28.49% variable",
    rating: 4.2,
    categories: ["cashback", "no-fee", "shopping"],
    topFor: null,
    keywords: ["apple", "iphone", "daily cash", "wallet", "usa", "titanium"],
    highlights: [
      "3% Daily Cash at Apple & select merchants",
      "2% with Apple Pay",
      "1% when using the physical card",
      "No fees — late, foreign, or annual",
    ],
    description:
      "Simple U.S. rewards card tied to Apple Wallet — Daily Cash and a clean fee structure.",
    applyUrl: "https://www.apple.com/apple-card/",
    gradient: "linear-gradient(135deg, #d4d4d4 0%, #f5f5f5 40%, #a8a8a8 100%)",
    accent: "#1a1a1a",
    textDark: true,
  },
  {
    id: "us-bank-altitude-reserve",
    name: "U.S. Bank Altitude® Reserve Visa Infinite® Card",
    issuer: "U.S. Bank",
    network: "Visa",
    annualFee: 400,
    welcomeBonus: "50,000 points",
    welcomeBonusValue: 750,
    apr: "20.24%–27.24% variable",
    rating: 4.7,
    categories: ["travel", "points", "premium"],
    topFor: null,
    keywords: ["us bank", "usb", "mobile wallet", "altitude", "usa"],
    highlights: [
      "3x on mobile wallet & travel purchases",
      "1x on other purchases",
      "$325 annual travel & dining credit",
      "Priority Pass Select lounge access",
    ],
    description:
      "Premium U.S. Bank travel card with strong mobile-wallet earn and a credit that can offset the fee.",
    applyUrl: "https://www.usbank.com/credit-cards/altitude-reserve-visa-infinite-credit-card.html",
    gradient: "linear-gradient(135deg, #0a1628 0%, #1a3a5c 50%, #c0c0c0 100%)",
    accent: "#a8c5e2",
  },
  {
    id: "delta-skymiles-gold",
    name: "Delta SkyMiles® Gold American Express Card",
    issuer: "American Express",
    network: "Amex",
    annualFee: 150,
    welcomeBonus: "50,000 miles + Medallion Qualification Dollars offer",
    welcomeBonusValue: 500,
    apr: "See terms",
    rating: 4.4,
    categories: ["travel", "points", "airline"],
    topFor: null,
    keywords: ["delta", "skymiles", "airline", "sky club", "usa", "atlanta"],
    highlights: [
      "2x miles at restaurants & U.S. supermarkets",
      "2x on Delta purchases",
      "First checked bag free",
      "Priority boarding + $100 Delta flight credit (after $10k spend)",
    ],
    description:
      "Popular U.S. airline card for Delta flyers — free bag, boarding perks, and solid everyday earn.",
    applyUrl: "https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-gold-american-express-card/",
    gradient: "linear-gradient(135deg, #003366 0%, #c8102e 100%)",
    accent: "#ffffff",
  },
  {
    id: "united-explorer",
    name: "United® Explorer Card",
    issuer: "Chase",
    network: "Visa",
    annualFee: 150,
    welcomeBonus: "60,000 miles",
    welcomeBonusValue: 720,
    apr: "20.49%–27.49% variable",
    rating: 4.4,
    categories: ["travel", "points", "airline"],
    topFor: null,
    keywords: ["united", "mileageplus", "airline", "club", "usa"],
    highlights: [
      "2x on United purchases, dining & hotels",
      "Free first checked bag",
      "2 United Club one-time passes each year",
      "Priority boarding",
    ],
    description:
      "Solid mid-tier United Airlines card for U.S. travelers who want free bags and MileagePlus miles.",
    applyUrl: "https://creditcards.chase.com/travel-credit-cards/united/explorer",
    gradient: "linear-gradient(135deg, #002244 0%, #0055a5 60%, #1e90ff 100%)",
    accent: "#7ec8ff",
  },
  {
    id: "southwest-rapid-rewards-plus",
    name: "Southwest Rapid Rewards® Plus Credit Card",
    issuer: "Chase",
    network: "Visa",
    annualFee: 99,
    welcomeBonus: "50,000 points",
    welcomeBonusValue: 700,
    apr: "20.49%–27.49% variable",
    rating: 4.3,
    categories: ["travel", "points", "airline"],
    topFor: null,
    keywords: ["southwest", "rapid rewards", "companion pass", "usa", "domestic flights"],
    highlights: [
      "2x on Southwest purchases & Rapid Rewards hotel/car partners",
      "2x on local transit & commuting",
      "3,000 anniversary points each year",
      "EarlyBird Check-In & first two bags free",
    ],
    description:
      "U.S. domestic flight favorite — earns toward Southwest Companion Pass and free checked bags.",
    applyUrl: "https://creditcards.chase.com/travel-credit-cards/southwest/plus",
    gradient: "linear-gradient(135deg, #304cb2 0%, #ffbf27 100%)",
    accent: "#1a1a1a",
  },
  {
    id: "citi-strata-premier",
    name: "Citi Strata Premier® Card",
    issuer: "Citi",
    network: "Mastercard",
    annualFee: 95,
    welcomeBonus: "60,000 ThankYou® Points",
    welcomeBonusValue: 750,
    apr: "19.24%–29.24% variable",
    rating: 4.6,
    categories: ["travel", "points", "dining", "groceries", "gas"],
    topFor: null,
    keywords: ["citi", "thankyou", "strata", "premier", "usa", "transfer partners"],
    highlights: [
      "3x on air travel & hotels",
      "3x at restaurants, supermarkets & gas stations",
      "1x on other purchases",
      "ThankYou transfer partners for travel",
    ],
    description:
      "Strong mid-tier U.S. points card with broad 3x categories and Citi ThankYou transfer partners.",
    applyUrl: "https://www.citi.com/credit-cards/citi-strata-premier-credit-card",
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #4a1942 50%, #8b3a62 100%)",
    accent: "#e8a0bf",
  },
  {
    id: "wells-fargo-autograph",
    name: "Wells Fargo Autograph® Card",
    issuer: "Wells Fargo",
    network: "Visa",
    annualFee: 0,
    welcomeBonus: "20,000 bonus points",
    welcomeBonusValue: 200,
    apr: "20.24%–29.99% variable",
    rating: 4.5,
    categories: ["travel", "points", "no-fee", "dining", "gas"],
    topFor: null,
    keywords: ["wells fargo", "autograph", "usa", "phone plans", "streaming"],
    highlights: [
      "3x on restaurants, travel, gas, transit, streaming & phone plans",
      "1x on other purchases",
      "No annual fee",
      "Cell phone protection",
    ],
    description:
      "No-fee U.S. rewards card with 3x across many everyday categories — great everyday earn rates.",
    applyUrl: "https://creditcards.wellsfargo.com/autograph-visa-credit-card/",
    gradient: "linear-gradient(135deg, #1a1a1a 0%, #d71e28 80%, #ff4d4d 100%)",
    accent: "#ffb3b8",
  },
  {
    id: "robinhood-gold-card",
    name: "Robinhood Gold Card",
    issuer: "Robinhood",
    network: "Mastercard",
    annualFee: 0,
    feeNote: "Requires Robinhood Gold ($5/mo or $50/yr)",
    welcomeBonus: "None (ongoing 3% cash back)",
    welcomeBonusValue: 0,
    apr: "19.99%–32.99% variable",
    rating: 4.8,
    categories: ["cashback", "no-fee", "travel"],
    topFor: null,
    keywords: [
      "robinhood",
      "gold card",
      "3% cash back",
      "flat rate",
      "brokerage",
      "invest",
      "usa",
    ],
    highlights: [
      "3% cash back on all eligible purchases",
      "5% on travel booked through Robinhood’s portal",
      "No annual fee on the card itself",
      "Redeem rewards into your Robinhood account",
    ],
    description:
      "Industry-leading flat 3% cash back on nearly everything. Card has no annual fee, but requires an active Robinhood Gold membership ($50/yr).",
    applyUrl: "https://robinhood.com/creditcard/",
    gradient: "linear-gradient(135deg, #0d0d0d 0%, #1a1a1a 40%, #c9a227 100%)",
    accent: "#00c805",
  },
];

// Normalize: every card in this catalog is a U.S. product
CREDIT_CARDS.forEach((card) => {
  card.country = "US";
  card.region = "United States";
  card.currency = "USD";
  if (!card.keywords) card.keywords = [];
  card.keywords = [
    ...card.keywords,
    "us",
    "usa",
    "united states",
    "american",
    "us credit card",
    card.issuer.toLowerCase(),
  ];
});

const TOP_PICK_LABELS = {
  travel: { title: "Best for Travel", emoji: "✈️", blurb: "Points, lounges & U.S. trip perks" },
  cashback: { title: "Best for Cash Back", emoji: "💵", blurb: "Simple unlimited U.S. rewards" },
  dining: { title: "Best for Dining", emoji: "🍽️", blurb: "Restaurants & food delivery" },
  groceries: { title: "Best for Groceries", emoji: "🛒", blurb: "U.S. supermarkets & essentials" },
  gas: { title: "Best for Gas", emoji: "⛽", blurb: "Fuel up with higher rewards" },
  business: { title: "Best for Business", emoji: "💼", blurb: "U.S. freelancers & SMBs" },
  student: { title: "Best for Students", emoji: "🎓", blurb: "Build U.S. credit, earn rewards" },
};
